#https://hugoloveit.com/zh-cn/theme-documentation-basics/#site-configuration
defaultContentLanguage = "zh-cn"
languageCode = "zh-CN"
title = "lyer's blog"
theme = "LoveIt"

[params]
  version = "0.2.X"
  [params.footer]
    enable = true
    hugo = true
    copyright = true
    author = true
    since = 2021
    icp = ""
    license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
    # 主页配置

  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      avatarURL = "https://pic4.zhimg.com/v2-e263475646652726731e13e44b5d2479_im.jpg"
      subtitle = "Hello,我叫lyer,热爱Linux,喜欢和有趣的人交朋友,大家一起变有趣吧~"
      typeit = true
      social = true
    [params.home.posts]
      enable = true
      paginate = 6

  [params.social]
      GitHub = "biningo"
      Twitter = "biningo2"
      Telegram = "icepan"
      Email = "icepan@aliyun.com"
      RSS = true
  [params.page]
    [params.page.comment]
        enable = true
        [params.page.comment.gitalk]
          enable = true
          owner = "biningo"
          repo = "hugo-blog-gittalk"
          clientId = "c8f473d59880800a7453"
          clientSecret = "7aa3dd0bcf966dee0a057e06eaf205caeb86b8e0"
	[params.search]
  	enable = true
  	# 搜索引擎的类型 ("lunr", "algolia")
  	type = "algolia"
  	# 文章内容最长索引长度
  	contentLength = 4000
  	# 搜索框的占位提示语
  	placeholder = ""
  	# LoveIt 新增 | 0.2.1 最大结果数目
  	maxResultLength = 10
  	# LoveIt 新增 | 0.2.3 结果内容片段长度
  	snippetLength = 50
  	# LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
  	highlightTag = "em"
  	# LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
  	absoluteURL = false
[menu]
  [[menu.main]]
    identifier = "archive"
    name = "archive"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    name = "tag"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    name = "category"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    identifier = "book"
    name = "book"
    url = "/book"
    weight = 4
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about"
    weight = 5



#语法高亮设置
[markup]
  [markup.highlight]
    noClasses = false

# 作者配置
[author]
  name = "lyer"
  email = "icepan@aliyun.com"
  link = "https://icepan.cloud"


[Permalinks]
  posts = ":year/:month/:day/:filename"
